version: "3"
services:
  nginx:
    ports:
      - "5000:80"
  node-app:
    build: .
    image: ducthanh/node-app
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=test
      - MONGO_PASSWORD=test
      - SESSION_SECRET=test
    command: npm run dev
    # env_file:
    #   - ./.env
